from pathlib import Path

from run_pipeline import run_pipeline


ROOT = Path(__file__).resolve().parents[1]


def main():
    style = {
        "style_name": "悬疑电影写实风格",
        "rendering": "写实电影摄影，轻微胶片颗粒",
        "color_palette": "低饱和冷色，红色作为视觉强调",
        "period": "当代旧公寓",
        "lighting": "夜间低调照明，柔和阴影",
    }
    outputs = run_pipeline(
        ROOT / "examples" / "输入剧本.txt",
        ROOT / "examples",
        "red_key_demo",
        style,
    )
    print(
        "Chinese example regenerated by deterministic code: "
        f"{len(outputs['storyboard.json']['shots'])} shots."
    )


if __name__ == "__main__":
    main()

